#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CiklumTweets.Resource", IsApplication=true)]

namespace CiklumTweets
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ciklum_logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int delete_image = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int favourite_image = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int favourite_image_nonactive = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int navigation_shape = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int row_divider = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int toast_style = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int twitter_logo = 2130837514;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int List = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int buttonClearFavourites = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int buttonFavourites = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int buttonMoreFooter = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int frameLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int imageButtonDeleteFavourite = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int imageButtonFavourite = 2131034126;
			
			// aapt resource value: 0x7f050005
			public const int imageCiklumLogo = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int imageTwitter = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int linearBottomLayout = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayoutRow = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int relativeLayoutDate = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int textViewDate = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int textViewDateFavourite = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int textViewMessage = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int textViewMessageFavourite = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int view = 2131034113;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FavouritesActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FooterView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RowFavourite = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RowView = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
